export enum CustomizationCategory {
  PAINT = 'PAINT',
  WHEELS = 'WHEELS',
  BODY_KIT = 'BODY_KIT',
  SPOILER = 'SPOILER',
  INTERIOR_SEAT = 'INTERIOR_SEAT',
  INTERIOR_DASHBOARD = 'INTERIOR_DASHBOARD',
  TRIM_LEVEL = 'TRIM_LEVEL',
  DECAL = 'DECAL',
}
